# Generated by Django 2.0.2 on 2018-02-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter the name of the book', max_length=50)),
                ('book_genre', models.CharField(help_text='Enter the genre', max_length=20)),
                ('book_release_date', models.DateField(help_text='Enter the release date', max_length=10)),
                ('book_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
    ]
