# Generated by Django 2.0.2 on 2018-02-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
