# Generated by Django 2.0.2 on 2018-02-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180228_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('Complaint_No', models.CharField(help_text='Enter Complain No', max_length=10, primary_key=True, serialize=False)),
                ('Content', models.CharField(help_text='Enter Content', max_length=200)),
                ('Date_of_Issue', models.DateField(help_text='Enter the date of issue', max_length=10)),
            ],
            options={
                'ordering': ['Complaint_No'],
            },
        ),
        migrations.CreateModel(
            name='Member_Registration',
            fields=[
                ('Member_ID', models.CharField(help_text='Enter Member ID', max_length=10, primary_key=True, serialize=False)),
                ('Flat_No', models.CharField(help_text='Enter a Flat No', max_length=5)),
                ('Owner_Name', models.CharField(help_text='Enter Owner Name', max_length=30)),
                ('Purchase_Date', models.DateField(help_text='Enter the date of purchase', max_length=10)),
                ('Mobile_No', models.IntegerField(help_text='Enter your Mobile Number')),
                ('Email_ID', models.EmailField(help_text='Enter your Email ID', max_length=50)),
            ],
            options={
                'ordering': ['Flat_No'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('Notice_No', models.CharField(help_text='Enter Notice No', max_length=10, primary_key=True, serialize=False)),
                ('No_of_Pages', models.IntegerField(help_text='Enter a No of pages')),
                ('Content', models.CharField(help_text='Enter Content', max_length=200)),
                ('Date_of_Issue', models.DateField(help_text='Enter the date of issue', max_length=10)),
                ('Date_of_Expiry', models.DateField(help_text='Enter the date of expiry', max_length=10)),
            ],
            options={
                'ordering': ['Notice_No'],
            },
        ),
        migrations.CreateModel(
            name='Rent_Registration',
            fields=[
                ('Rent_ID', models.CharField(help_text='Enter Rent ID', max_length=10, primary_key=True, serialize=False)),
                ('Flat_No', models.CharField(help_text='Enter a Flat No', max_length=5)),
                ('Rent_Name', models.CharField(help_text='Enter the Name of the person', max_length=30)),
                ('Date_of_Lease', models.DateField(help_text='Enter the date when the lease will end', max_length=10)),
                ('Mobile_No', models.IntegerField(help_text='Enter your Mobile Number')),
                ('Email_ID', models.EmailField(help_text='Enter your Email ID', max_length=50)),
            ],
            options={
                'ordering': ['Flat_No'],
            },
        ),
        migrations.CreateModel(
            name='Society_Registration',
            fields=[
                ('Society_ID', models.CharField(help_text='Enter Society ID', max_length=10, primary_key=True, serialize=False)),
                ('Society_name', models.CharField(help_text='Enter a Society name', max_length=10)),
                ('Socety_Address', models.CharField(help_text='Enter Society Address', max_length=50)),
                ('No_of_Flats', models.IntegerField(help_text='Enter the number of flats')),
                ('Occupied_Flats', models.IntegerField(help_text='Enter the number of occupied flats')),
                ('No_of_Parking', models.IntegerField(help_text='Enter the number of parking')),
                ('No_of_Member', models.IntegerField(help_text='Enter the number of people living in the building')),
            ],
            options={
                'ordering': ['Society_name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='complaints',
            name='Member_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Member_Registration'),
        ),
    ]
