# Generated by Django 2.0.2 on 2018-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180305_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_registration',
            name='Member_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
