# Generated by Django 2.0.2 on 2018-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180305_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society_registration',
            options={'ordering': ['Society_Name']},
        ),
        migrations.RenameField(
            model_name='society_registration',
            old_name='Society_name',
            new_name='Society_Name',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Notice_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rent_registration',
            name='Rent_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='society_registration',
            name='Society_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
