# Generated by Django 2.0.2 on 2018-03-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180305_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_registration',
            old_name='Rent_Name',
            new_name='Tenant_Name',
        ),
    ]
