# Generated by Django 2.0.2 on 2018-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180314_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Member_ID',
            new_name='Flat_No',
        ),
    ]
