# Generated by Django 2.0.2 on 2018-03-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180328_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_registration',
            name='Main_amount',
        ),
    ]
