# Generated by Django 2.0.2 on 2018-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_member_registration_main_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_registration',
            name='Parking',
            field=models.IntegerField(default='1', help_text='Enter the number of parking you have'),
        ),
    ]
